---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rapids-cephfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  storageClassName: example-storagecluster-cephfs
